apiVersion: v1
kind: Service
metadata:
  name: traderoo
  labels:
    app.kubernetes.io/name: traderoo
    app.kubernetes.io/part-of: traderoo
spec:
  selector:
    app.kubernetes.io/name: traderoo
  ports:
    - name: http
      port: 8000
      targetPort: http
