apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traderoo
  namespace: argocd
spec:
  project: default
  source:
    # Replace this placeholder with your actual GitHub repository URL.
    repoURL: https://github.com/h3ow3d/traderoo.git
    targetRevision: HEAD
    path: applications/traderoo/k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: traderoo-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
