apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traderoo-poc
  namespace: argocd
spec:
  project: traderoo-poc
  source:
    # Replace this placeholder with your actual GitHub repository URL.
    repoURL: https://github.com/h3ow3d/traderoo.git
    targetRevision: HEAD
    path: applications/traderoo/k8s/overlays/poc
  destination:
    server: https://kubernetes.default.svc
    namespace: traderoo-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
