{{- range $env := .Values.applicationEnvironments }}
{{- if $env.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $env.projectName }}
  namespace: {{ $.Values.argocdNamespace }}
  labels:
    {{- include "platform-services.labels" $ | nindent 4 }}
spec:
  description: {{ $env.description | quote }}
  sourceRepos:
    {{- toYaml $env.sourceRepos | nindent 4 }}
  destinations:
    {{- toYaml $env.destinations | nindent 4 }}
{{- if $env.clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{- toYaml $env.clusterResourceWhitelist | nindent 4 }}
{{- else }}
  clusterResourceWhitelist: []
{{- end }}
{{- end }}
{{- end }}
