{{- range $env := .Values.applicationEnvironments }}
{{- if $env.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $env.namespace }}
  labels:
    {{- include "platform-services.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
